//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seaboard.Intranet.BusinessLogic.DGIIServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPlacaResult", Namespace="http://dgii.gov.do/")]
    [System.SerializableAttribute()]
    public partial class GetPlacaResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Seaboard.Intranet.BusinessLogic.DGIIServiceClient.PlacaModel placaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Seaboard.Intranet.BusinessLogic.DGIIServiceClient.OposiciónModel[] oposiciónesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.PlacaModel placa {
            get {
                return this.placaField;
            }
            set {
                if ((object.ReferenceEquals(this.placaField, value) != true)) {
                    this.placaField = value;
                    this.RaisePropertyChanged("placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.OposiciónModel[] oposiciónes {
            get {
                return this.oposiciónesField;
            }
            set {
                if ((object.ReferenceEquals(this.oposiciónesField, value) != true)) {
                    this.oposiciónesField = value;
                    this.RaisePropertyChanged("oposiciónes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlacaModel", Namespace="http://dgii.gov.do/")]
    [System.SerializableAttribute()]
    public partial class PlacaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MARCA_VEHICULOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MODELO_VEHICULOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ANO_FABRICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PLACAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RNC_CEDULA_PROPIETARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MARCA_VEHICULO {
            get {
                return this.MARCA_VEHICULOField;
            }
            set {
                if ((object.ReferenceEquals(this.MARCA_VEHICULOField, value) != true)) {
                    this.MARCA_VEHICULOField = value;
                    this.RaisePropertyChanged("MARCA_VEHICULO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MODELO_VEHICULO {
            get {
                return this.MODELO_VEHICULOField;
            }
            set {
                if ((object.ReferenceEquals(this.MODELO_VEHICULOField, value) != true)) {
                    this.MODELO_VEHICULOField = value;
                    this.RaisePropertyChanged("MODELO_VEHICULO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string COLOR {
            get {
                return this.COLORField;
            }
            set {
                if ((object.ReferenceEquals(this.COLORField, value) != true)) {
                    this.COLORField = value;
                    this.RaisePropertyChanged("COLOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ANO_FABRICACION {
            get {
                return this.ANO_FABRICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.ANO_FABRICACIONField, value) != true)) {
                    this.ANO_FABRICACIONField = value;
                    this.RaisePropertyChanged("ANO_FABRICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PLACA {
            get {
                return this.PLACAField;
            }
            set {
                if ((object.ReferenceEquals(this.PLACAField, value) != true)) {
                    this.PLACAField = value;
                    this.RaisePropertyChanged("PLACA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RNC_CEDULA_PROPIETARIO {
            get {
                return this.RNC_CEDULA_PROPIETARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.RNC_CEDULA_PROPIETARIOField, value) != true)) {
                    this.RNC_CEDULA_PROPIETARIOField = value;
                    this.RaisePropertyChanged("RNC_CEDULA_PROPIETARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OposiciónModel", Namespace="http://dgii.gov.do/")]
    [System.SerializableAttribute()]
    public partial class OposiciónModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long NUMERO_OPOSICIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_OPOSICIONField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long NUMERO_OPOSICION {
            get {
                return this.NUMERO_OPOSICIONField;
            }
            set {
                if ((this.NUMERO_OPOSICIONField.Equals(value) != true)) {
                    this.NUMERO_OPOSICIONField = value;
                    this.RaisePropertyChanged("NUMERO_OPOSICION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TIPO_OPOSICION {
            get {
                return this.TIPO_OPOSICIONField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_OPOSICIONField, value) != true)) {
                    this.TIPO_OPOSICIONField = value;
                    this.RaisePropertyChanged("TIPO_OPOSICION");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dgii.gov.do/", ConfigurationName="DGIIServiceClient.WSMovilDGIISoap")]
    public interface WSMovilDGIISoap {
        
        // CODEGEN: Generating message contract since element name value from namespace http://dgii.gov.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetContribuyentes", ReplyAction="*")]
        Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesResponse GetContribuyentes(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetContribuyentes", ReplyAction="*")]
        System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesResponse> GetContribuyentesAsync(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesRequest request);
        
        // CODEGEN: Generating message contract since element name value from namespace http://dgii.gov.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetContribuyentesCount", ReplyAction="*")]
        Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountResponse GetContribuyentesCount(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetContribuyentesCount", ReplyAction="*")]
        System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountResponse> GetContribuyentesCountAsync(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountRequest request);
        
        // CODEGEN: Generating message contract since element name codigoBusqueda from namespace http://dgii.gov.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetDocumento", ReplyAction="*")]
        Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoResponse GetDocumento(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoResponse> GetDocumentoAsync(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoRequest request);
        
        // CODEGEN: Generating message contract since element name value from namespace http://dgii.gov.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetVehiculoPorDATAMATRIX", ReplyAction="*")]
        Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXResponse GetVehiculoPorDATAMATRIX(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetVehiculoPorDATAMATRIX", ReplyAction="*")]
        System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXResponse> GetVehiculoPorDATAMATRIXAsync(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXRequest request);
        
        // CODEGEN: Generating message contract since element name RNC from namespace http://dgii.gov.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetNCF", ReplyAction="*")]
        Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFResponse GetNCF(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetNCF", ReplyAction="*")]
        System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFResponse> GetNCFAsync(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFRequest request);
        
        // CODEGEN: Generating message contract since element name RNC from namespace http://dgii.gov.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetPlaca", ReplyAction="*")]
        Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaResponse GetPlaca(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetPlaca", ReplyAction="*")]
        System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaResponse> GetPlacaAsync(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContribuyentesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContribuyentes", Namespace="http://dgii.gov.do/", Order=0)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesRequestBody Body;
        
        public GetContribuyentesRequest() {
        }
        
        public GetContribuyentesRequest(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetContribuyentesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int patronBusqueda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int inicioFilas;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int filaFilas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IMEI;
        
        public GetContribuyentesRequestBody() {
        }
        
        public GetContribuyentesRequestBody(string value, int patronBusqueda, int inicioFilas, int filaFilas, string IMEI) {
            this.value = value;
            this.patronBusqueda = patronBusqueda;
            this.inicioFilas = inicioFilas;
            this.filaFilas = filaFilas;
            this.IMEI = IMEI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContribuyentesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContribuyentesResponse", Namespace="http://dgii.gov.do/", Order=0)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesResponseBody Body;
        
        public GetContribuyentesResponse() {
        }
        
        public GetContribuyentesResponse(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetContribuyentesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetContribuyentesResult;
        
        public GetContribuyentesResponseBody() {
        }
        
        public GetContribuyentesResponseBody(string GetContribuyentesResult) {
            this.GetContribuyentesResult = GetContribuyentesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContribuyentesCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContribuyentesCount", Namespace="http://dgii.gov.do/", Order=0)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountRequestBody Body;
        
        public GetContribuyentesCountRequest() {
        }
        
        public GetContribuyentesCountRequest(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetContribuyentesCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IMEI;
        
        public GetContribuyentesCountRequestBody() {
        }
        
        public GetContribuyentesCountRequestBody(string value, string IMEI) {
            this.value = value;
            this.IMEI = IMEI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContribuyentesCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContribuyentesCountResponse", Namespace="http://dgii.gov.do/", Order=0)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountResponseBody Body;
        
        public GetContribuyentesCountResponse() {
        }
        
        public GetContribuyentesCountResponse(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetContribuyentesCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetContribuyentesCountResult;
        
        public GetContribuyentesCountResponseBody() {
        }
        
        public GetContribuyentesCountResponseBody(string GetContribuyentesCountResult) {
            this.GetContribuyentesCountResult = GetContribuyentesCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumento", Namespace="http://dgii.gov.do/", Order=0)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoRequestBody Body;
        
        public GetDocumentoRequest() {
        }
        
        public GetDocumentoRequest(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetDocumentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigoBusqueda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int patronBusqueda;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMEI;
        
        public GetDocumentoRequestBody() {
        }
        
        public GetDocumentoRequestBody(string codigoBusqueda, int patronBusqueda, string IMEI) {
            this.codigoBusqueda = codigoBusqueda;
            this.patronBusqueda = patronBusqueda;
            this.IMEI = IMEI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentoResponse", Namespace="http://dgii.gov.do/", Order=0)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoResponseBody Body;
        
        public GetDocumentoResponse() {
        }
        
        public GetDocumentoResponse(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetDocumentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDocumentoResult;
        
        public GetDocumentoResponseBody() {
        }
        
        public GetDocumentoResponseBody(string GetDocumentoResult) {
            this.GetDocumentoResult = GetDocumentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVehiculoPorDATAMATRIXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVehiculoPorDATAMATRIX", Namespace="http://dgii.gov.do/", Order=0)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXRequestBody Body;
        
        public GetVehiculoPorDATAMATRIXRequest() {
        }
        
        public GetVehiculoPorDATAMATRIXRequest(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetVehiculoPorDATAMATRIXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IMEI;
        
        public GetVehiculoPorDATAMATRIXRequestBody() {
        }
        
        public GetVehiculoPorDATAMATRIXRequestBody(string value, string IMEI) {
            this.value = value;
            this.IMEI = IMEI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVehiculoPorDATAMATRIXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVehiculoPorDATAMATRIXResponse", Namespace="http://dgii.gov.do/", Order=0)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXResponseBody Body;
        
        public GetVehiculoPorDATAMATRIXResponse() {
        }
        
        public GetVehiculoPorDATAMATRIXResponse(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetVehiculoPorDATAMATRIXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetVehiculoPorDATAMATRIXResult;
        
        public GetVehiculoPorDATAMATRIXResponseBody() {
        }
        
        public GetVehiculoPorDATAMATRIXResponseBody(string GetVehiculoPorDATAMATRIXResult) {
            this.GetVehiculoPorDATAMATRIXResult = GetVehiculoPorDATAMATRIXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNCFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNCF", Namespace="http://dgii.gov.do/", Order=0)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFRequestBody Body;
        
        public GetNCFRequest() {
        }
        
        public GetNCFRequest(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetNCFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RNC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NCF;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMEI;
        
        public GetNCFRequestBody() {
        }
        
        public GetNCFRequestBody(string RNC, string NCF, string IMEI) {
            this.RNC = RNC;
            this.NCF = NCF;
            this.IMEI = IMEI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNCFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNCFResponse", Namespace="http://dgii.gov.do/", Order=0)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFResponseBody Body;
        
        public GetNCFResponse() {
        }
        
        public GetNCFResponse(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetNCFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNCFResult;
        
        public GetNCFResponseBody() {
        }
        
        public GetNCFResponseBody(string GetNCFResult) {
            this.GetNCFResult = GetNCFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlacaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlaca", Namespace="http://dgii.gov.do/", Order=0)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaRequestBody Body;
        
        public GetPlacaRequest() {
        }
        
        public GetPlacaRequest(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetPlacaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RNC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Placa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMEI;
        
        public GetPlacaRequestBody() {
        }
        
        public GetPlacaRequestBody(string RNC, string Placa, string IMEI) {
            this.RNC = RNC;
            this.Placa = Placa;
            this.IMEI = IMEI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlacaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlacaResponse", Namespace="http://dgii.gov.do/", Order=0)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaResponseBody Body;
        
        public GetPlacaResponse() {
        }
        
        public GetPlacaResponse(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetPlacaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaResult GetPlacaResult;
        
        public GetPlacaResponseBody() {
        }
        
        public GetPlacaResponseBody(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaResult GetPlacaResult) {
            this.GetPlacaResult = GetPlacaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSMovilDGIISoapChannel : Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSMovilDGIISoapClient : System.ServiceModel.ClientBase<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap>, Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap {
        
        public WSMovilDGIISoapClient() {
        }
        
        public WSMovilDGIISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSMovilDGIISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMovilDGIISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMovilDGIISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesResponse Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap.GetContribuyentes(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesRequest request) {
            return base.Channel.GetContribuyentes(request);
        }
        
        public string GetContribuyentes(string value, int patronBusqueda, int inicioFilas, int filaFilas, string IMEI) {
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesRequest inValue = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesRequest();
            inValue.Body = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesRequestBody();
            inValue.Body.value = value;
            inValue.Body.patronBusqueda = patronBusqueda;
            inValue.Body.inicioFilas = inicioFilas;
            inValue.Body.filaFilas = filaFilas;
            inValue.Body.IMEI = IMEI;
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesResponse retVal = ((Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap)(this)).GetContribuyentes(inValue);
            return retVal.Body.GetContribuyentesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesResponse> Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap.GetContribuyentesAsync(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesRequest request) {
            return base.Channel.GetContribuyentesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesResponse> GetContribuyentesAsync(string value, int patronBusqueda, int inicioFilas, int filaFilas, string IMEI) {
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesRequest inValue = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesRequest();
            inValue.Body = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesRequestBody();
            inValue.Body.value = value;
            inValue.Body.patronBusqueda = patronBusqueda;
            inValue.Body.inicioFilas = inicioFilas;
            inValue.Body.filaFilas = filaFilas;
            inValue.Body.IMEI = IMEI;
            return ((Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap)(this)).GetContribuyentesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountResponse Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap.GetContribuyentesCount(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountRequest request) {
            return base.Channel.GetContribuyentesCount(request);
        }
        
        public string GetContribuyentesCount(string value, string IMEI) {
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountRequest inValue = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountRequest();
            inValue.Body = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountRequestBody();
            inValue.Body.value = value;
            inValue.Body.IMEI = IMEI;
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountResponse retVal = ((Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap)(this)).GetContribuyentesCount(inValue);
            return retVal.Body.GetContribuyentesCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountResponse> Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap.GetContribuyentesCountAsync(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountRequest request) {
            return base.Channel.GetContribuyentesCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountResponse> GetContribuyentesCountAsync(string value, string IMEI) {
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountRequest inValue = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountRequest();
            inValue.Body = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetContribuyentesCountRequestBody();
            inValue.Body.value = value;
            inValue.Body.IMEI = IMEI;
            return ((Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap)(this)).GetContribuyentesCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoResponse Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap.GetDocumento(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoRequest request) {
            return base.Channel.GetDocumento(request);
        }
        
        public string GetDocumento(string codigoBusqueda, int patronBusqueda, string IMEI) {
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoRequest inValue = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoRequest();
            inValue.Body = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoRequestBody();
            inValue.Body.codigoBusqueda = codigoBusqueda;
            inValue.Body.patronBusqueda = patronBusqueda;
            inValue.Body.IMEI = IMEI;
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoResponse retVal = ((Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap)(this)).GetDocumento(inValue);
            return retVal.Body.GetDocumentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoResponse> Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap.GetDocumentoAsync(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoRequest request) {
            return base.Channel.GetDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoResponse> GetDocumentoAsync(string codigoBusqueda, int patronBusqueda, string IMEI) {
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoRequest inValue = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoRequest();
            inValue.Body = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetDocumentoRequestBody();
            inValue.Body.codigoBusqueda = codigoBusqueda;
            inValue.Body.patronBusqueda = patronBusqueda;
            inValue.Body.IMEI = IMEI;
            return ((Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap)(this)).GetDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXResponse Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap.GetVehiculoPorDATAMATRIX(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXRequest request) {
            return base.Channel.GetVehiculoPorDATAMATRIX(request);
        }
        
        public string GetVehiculoPorDATAMATRIX(string value, string IMEI) {
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXRequest inValue = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXRequest();
            inValue.Body = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXRequestBody();
            inValue.Body.value = value;
            inValue.Body.IMEI = IMEI;
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXResponse retVal = ((Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap)(this)).GetVehiculoPorDATAMATRIX(inValue);
            return retVal.Body.GetVehiculoPorDATAMATRIXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXResponse> Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap.GetVehiculoPorDATAMATRIXAsync(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXRequest request) {
            return base.Channel.GetVehiculoPorDATAMATRIXAsync(request);
        }
        
        public System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXResponse> GetVehiculoPorDATAMATRIXAsync(string value, string IMEI) {
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXRequest inValue = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXRequest();
            inValue.Body = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetVehiculoPorDATAMATRIXRequestBody();
            inValue.Body.value = value;
            inValue.Body.IMEI = IMEI;
            return ((Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap)(this)).GetVehiculoPorDATAMATRIXAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFResponse Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap.GetNCF(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFRequest request) {
            return base.Channel.GetNCF(request);
        }
        
        public string GetNCF(string RNC, string NCF, string IMEI) {
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFRequest inValue = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFRequest();
            inValue.Body = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFRequestBody();
            inValue.Body.RNC = RNC;
            inValue.Body.NCF = NCF;
            inValue.Body.IMEI = IMEI;
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFResponse retVal = ((Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap)(this)).GetNCF(inValue);
            return retVal.Body.GetNCFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFResponse> Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap.GetNCFAsync(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFRequest request) {
            return base.Channel.GetNCFAsync(request);
        }
        
        public System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFResponse> GetNCFAsync(string RNC, string NCF, string IMEI) {
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFRequest inValue = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFRequest();
            inValue.Body = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetNCFRequestBody();
            inValue.Body.RNC = RNC;
            inValue.Body.NCF = NCF;
            inValue.Body.IMEI = IMEI;
            return ((Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap)(this)).GetNCFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaResponse Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap.GetPlaca(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaRequest request) {
            return base.Channel.GetPlaca(request);
        }
        
        public Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaResult GetPlaca(string RNC, string Placa, string IMEI) {
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaRequest inValue = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaRequest();
            inValue.Body = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaRequestBody();
            inValue.Body.RNC = RNC;
            inValue.Body.Placa = Placa;
            inValue.Body.IMEI = IMEI;
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaResponse retVal = ((Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap)(this)).GetPlaca(inValue);
            return retVal.Body.GetPlacaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaResponse> Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap.GetPlacaAsync(Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaRequest request) {
            return base.Channel.GetPlacaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaResponse> GetPlacaAsync(string RNC, string Placa, string IMEI) {
            Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaRequest inValue = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaRequest();
            inValue.Body = new Seaboard.Intranet.BusinessLogic.DGIIServiceClient.GetPlacaRequestBody();
            inValue.Body.RNC = RNC;
            inValue.Body.Placa = Placa;
            inValue.Body.IMEI = IMEI;
            return ((Seaboard.Intranet.BusinessLogic.DGIIServiceClient.WSMovilDGIISoap)(this)).GetPlacaAsync(inValue);
        }
    }
}
